[tool.poetry]
name = "memcache"
version = "0.10.0"
description = "Memcached client for Python"
readme = "README.md"
authors = ["An Long <aisk1988@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
hashring = "^1.5.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
black = "^20.8b1"
pytest = "^6.2.1"
pytest-asyncio = "^0.15.1"
Sphinx = "^4.0.2"
sphinx-rtd-theme = "^0.5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
